### PR TITLE
[paper] Use a symbol to make abs easier to read

### PR DESCRIPTION
**Pull request by freebroccolo**
I don't know if lambda is really appropriate there but having some sort of symbol makes it easier to read I think.

### CODE REVIEW

**Comment by jonsterling** [comment]
Hmmm, I am not sure. I have two concerns:

1. I don't want people to confuse this "meta"-`\lambda` with some object-lambda.
2. For abstractors/bound terms, it is standard to write something like `x.E`; for instance, consider the object expression `lam(x.E)`. It would be a bit odd to see something like `lam(λx. E)` outside of HOL or something.

Now, in these ABTs the bound terms are a little noisier, I'll grant, because I needed two abstractor slots (one for symbols, one for variables). What do you think? Is there anything else we can do that would make it easier to read?

**Comment by freebroccolo** [comment]
I had the same concern about using lambda with regards to confusion. One possibility could be to use a different style lambda (Jacobs does this for example, using a double struck lambda). Another thing that might help would be to replace the dot with something that stands out more, like a triangle. But that has other downsides.

**Comment by jonsterling** [comment]
Yeah... I guess my thinking is that the dot is a very standard way to represent binding, and so I think it would be confusing to do it in any other way. However, I will grant that the notation for the symbol & variable slots is noisy enough that it might distract from the dot.

**Comment by jonsterling** [comment]
One option would be a thicker-struck dot...

**Comment by freebroccolo** [comment]
What do you think of this double struck lambda?

**Comment by jonsterling** [comment]
I think it's a lot better than the normal lambda... But I still don't love it. I guess my perspective is that I would like to follow accepted & known notation as much as possible unless there is a reason not to; well, maybe the standard notation is unreadable enough that we should replace it, I'm not sure.

**Comment by jonsterling** [comment]
Ehh, I guess I could get used to the lambda if you feel strongly about it. It does look kind of cool.

**Comment by jonsterling** [comment]
(I'm a sucker for double-struck math symbols)

**Comment by freebroccolo** [comment]
Thanks :) I agree it's not perfect but I think it does help readability, particularly for the substitution parts. Do we still want to rework those to use simultaneous substitution btw?

**Comment by jonsterling** [comment]
@freebroccolo Yes, I think it would be great if we could rework the substitutions..

**Pull request merged**
