### PR TITLE
Implement #35 (sheaves & finite support)

### PR DESCRIPTION
**Pull request by jonsterling**
work in progress (#35), comments welcome

### CODE REVIEW

**Comment by jonsterling** [comment]
By the way, I wonder if there is a simpler way to present the operator signatures. I like viewing them through the Grothendieck construction because it makes it a lot more clear what it means to define an operator; without that, you just have to say "an operator is a family of sections in the operators presheaf", which isn't super intuitive I think, and doesn't really reflect "practice".

But I am worried that all this `pi^-1` stuff is just a bit too much; it makes sense, but it may be hard for the ready to tell whether it is an essential part of the definition, or just a supporting example meant to elicit an intuition.

**Comment by freebroccolo** [comment]
Regarding the operator signatures, I'm not sure. If you feel the current stuff about the fibers is too much of a distraction, I'd be okay with removing it. Maybe it'd be better in an appendix with expanded examples. Honestly, the reason I added it in the first place was just to clarify to myself what was actually going on there.

**Comment by jonsterling** [comment]
OK. I think that stuff can be pretty helpful, but I may think a bit about what we can do to make it a little more clear...

**Comment by jonsterling** [comment]
I think I'm going to merge this PR—enough improvements to the presentation have been made here that even if the sheaf thing turns out not to work (I'm pretty confident at this point that it does work, though), it would probably be better to just rip stuff out than to try and start over.

**Pull request merged**
